export const mainNav = [
     {
          title: 'Thời sự',
          path: 'https://vnexpress.net/thoi-su',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Góc nhìn',
          path: 'https://vnexpress.net/goc-nhin',
          subNav: [
               {title: 'Bình luận nhiều', path: ''},
               {title: 'Covid 19', path: ''},
               {title: 'Chính trị & chính sách', path: ''},
               {title: 'Y tế & sức khỏe', path: ''},
               {title: 'Kinh doanh & quản trị', path: ''},
               {title: 'Giáo dục & tri thức', path: ''},
               {title: 'Môi trường', path: ''},
               {title: 'Văn hóa & lối sống', path: ''},
               {title: 'Tác giả', path: ''},
          ],
     },
     {
          title: 'Thế giới',
          path: 'https://vnexpress.net/the-gioi',
          subNav: [
               {title: 'Tự liệu', path: ''},
               {title: 'Phân tích', path: ''},
               {title: 'Người Việt 5 châu', path: ''},
               {title: 'Cuộc sống đó đây', path: ''},
               {title: 'Quân sự', path: ''},
          ],
     },
     {
          title: 'Video',
          path: 'https://video.vnexpress.net/',
          subNav: [
               {title: 'Thời sự', path: ''},
               {title: 'Nhịp sống', path: ''},
               {title: 'Sports Life', path: ''},
               {title: 'Food', path: ''},
               {title: 'Cuộc sống 4.0', path: ''},
               {title: 'Tôi kể', path: ''},
               {title: 'Chuyện núi rừng', path: ''},
               {title: 'Tọa đàm kinh tế', path: ''},
               {title: 'Giải trí', path: ''},
               {title: 'Du lịch', path: ''},
               {title: 'Thế giới', path: ''},
               {title: 'Pháp luật', path: ''},
               {title: 'Kinh doanh', path: ''},
               {title: 'Khoa học', path: ''},
               {title: 'Giáo dục', path: ''},
               {title: 'Sức khỏe', path: ''},
          ],
     },
     {
          title: 'Podcasts',
          path: 'https://vnexpress.net/podcast',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Kinh doanh',
          path: 'https://vnexpress.net/kinh-doanh',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Khoa học',
          path: 'https://vnexpress.net/khoa-hoc',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Giải trí',
          path: 'https://vnexpress.net/giai-tri',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Thể thao',
          path: 'https://vnexpress.net/the-thao',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Pháp luật',
          path: 'https://vnexpress.net/phap-luat',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Giáo dục',
          path: 'https://vnexpress.net/giao-duc',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Sức khỏe',
          path: 'https://vnexpress.net/suc-khoe',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Đời sống',
          path: 'https://vnexpress.net/doi-song',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Du lịch',
          path: 'https://vnexpress.net/du-lich',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Số hóa',
          path: 'https://vnexpress.net/so-hoa',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Xe',
          path: 'https://vnexpress.net/xe',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Ý kiến',
          path: 'https://vnexpress.net/y-kien',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Tâm sự',
          path: 'https://vnexpress.net/tam-su',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
     {
          title: 'Hài',
          path: 'https://vnexpress.net/hai',
          subNav: [
               {title: 'Chính trị', path: ''},
               {title: 'Dân sinh', path: ''},
               {title: 'Giao thông', path: ''},
               {title: 'MeKong', path: ''},
               {title: 'Quỹ Hy vọng', path: ''},
               {title: 'Tết yêu thương', path: ''},
          ],
     },
]